/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:61d4d379-72a2-48a9-8fc0-b407d234f6fa",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_oV8PPDy8b",
    "aws_user_pools_web_client_id": "65a0dhnesi92objulvkc7a53g",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://4l6qzw6av5cs5gldaazsw6ri54.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wrdrh3yzrzcwnc5gl3n4xr6qde",
    "aws_cloud_logic_custom": [
        {
            "name": "reactauthrestcf",
            "endpoint": "https://2i9un9srmf.execute-api.us-west-2.amazonaws.com/reacthooks",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
